### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by chaoservices** [glpi-project/doc#6]
Assuming this is the repository for the current GLPI documentation, would you mind if I contribute as my time allows?

If so are there any considerations I should have beside branching and submitting merge requests?

**Comment by flegastelois** [comment]
Hi,

For sure you can contribute ! it will be greatly appreciated.
To discuss how you can do that, you can send an email to glpi@teclib.com.

Best regards,

**Comment by chaoservices** [comment]
I did email there after the 9.1 release, but no response. I'll ring again :)

**Comment by Armin83** [comment]
I also wrote a email and got no answer.

**Comment by trasher** [comment]
Hello,

Thank you for having contacted us.
Documentation is a big general issue on GLPi project, and we'd like to address it.
We have decided to start with the developer doc, to test different scenarios. We ended us using [Sphinx](http://www.sphinx-doc.org), [readthedocs](http://rtfd.io) and [transifex](https://www.transifex.com) (for translations), and are really happy with the results (see [developper documentation](http://glpi-developer-documentation.readthedocs.io/en/master/) or [plugins documentation](http://glpi-plugins.readthedocs.io/) for example).
We're currently evaluating the possibility to switch the user doc to the same system.
Unfortunately, because of an important amount of work for releasing GLPi 9.1, we haven't yet finished the job.

We plan to work on the user doc in early 2017, and would be very happy if you want to join, and propose to come back to you when we are ready to start !

We apologize not to answer your requests before; we'll do our best and keep you in touch.

Thank you for using and promoting GLPi.

**Comment by trasher** [comment]
Hello,

I've been able to take some time to work on the doc; I've explained the plan on the mailing list:
https://mail.gna.org/public/glpi-doc/2017-04/msg00001.html

Thank you!
